version: '3.7'

services:
    idchain:
        image: 'songadao/idchain-node:1.0'
        volumes:
            - './idchain_full/:/idchain'
        environment:
            - 'EXTRA_OPTS=--gcmode archive --http.api eth,net,web3,txpool'
            - 'SYNCMODE=full'
        ports:
            # - '8545:8545'
            # - '8546:8546'
            - '30329:30329'
            - '30329:30329/udp'
        restart: unless-stopped

    # idchain:
    #     image: 'songadao/idchain-node:1.0'
    #     volumes:
    #         - './idchain_light/:/idchain'
    #     environment:
    #         - 'EXTRA_OPTS=--http.api eth,net,web3,txpool'
    #         - 'SYNCMODE=light'
    #     ports:
    #         # - '8545:8545'
    #         # - '8546:8546'
    #         - '30329:30329'
    #         - '30329:30329/udp'
    #     restart: unless-stopped

    brightid_registration_relay:
        image: 'songadao/brightid-registration-relay:1.0'
        env_file:
            - .env.brightid_registration_relay
        restart: unless-stopped

    nginx:
        image: 'nginx:1.21'
        volumes:
            - ./nginx/conf/:/etc/nginx/conf.d/:ro
            - ./nginx/dhparam/:/etc/nginx/dhparam/:ro
            - ./nginx/htpasswd/:/etc/nginx/htpasswd/:rw
            - ./nginx/www/html/:/var/www/html/:ro
            - ./nginx/www/idchain-registration/:/var/www/idchain-registration/:ro
            - ./nginx/www/brightid-registration/:/var/www/brightid-registration/:ro
            - ./certbot/www/:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - '80:80'
            - '443:443'
        restart: unless-stopped

    certbot:
        image: certbot/certbot:v1.22.0
        volumes:
            - ./certbot/logs/:/var/log/letsencrypt/:rw
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
