version: '3.7'

services:
    brightid_registration_relay:
        image: 'songadao/brightid-registration-relay:1.0'
        env_file:
            - .env
        restart: unless-stopped

networks:
    default:
        name: sad_external_http
        external: true
