version: '3.7'

services:
    songadao_pfp_builder_api:
        image: 'songadao/pfp_builder_api:1.0'
        env_file:
            - .env
        restart: unless-stopped

networks:
    default:
        name: sad_external_http
        external: true
